#!/usr/bin/env node
/**
 * build-scripts.js
 *
 * Bundles the validator scripts with their npm dependencies inlined, so the
 * Claude Code plugin install (which copies files but doesn't run `npm install`)
 * still produces working validators on the user's machine.
 *
 *   node tools/build-scripts.js          # rebuild bundles
 *   node tools/build-scripts.js --check  # exit 1 if bundles are stale (CI use)
 *
 * Sources live under plugins/axiom/skills/axiom/scripts/_src/ ; bundles overwrite
 * the same filenames at plugins/axiom/skills/axiom/scripts/. Tests, SKILL.md,
 * and npm scripts reference the bundles.
 */

const {build} = require('esbuild')
const {readFileSync, writeFileSync, mkdtempSync, rmSync} = require('node:fs')
const {join, resolve, dirname} = require('node:path')
const {tmpdir} = require('node:os')

const SCRIPTS = [
    {src: 'plugins/axiom/skills/axiom/scripts/_src/validate-no-code.js',
     out: 'plugins/axiom/skills/axiom/scripts/validate-no-code.js'},
    {src: 'plugins/axiom/skills/axiom/scripts/_src/validate-coded.js',
     out: 'plugins/axiom/skills/axiom/scripts/validate-coded.js'}
]

const BANNER = '/*! Generated by tools/build-scripts.js — DO NOT EDIT directly. Source lives in scripts/_src/. Rebuild: `npm run build:scripts`. */'

const CHECK_ONLY = process.argv.includes('--check')
const ROOT = resolve(__dirname, '..')

async function buildOne({src, out}) {
    const absSrc = resolve(ROOT, src)
    const absOut = resolve(ROOT, out)
    const result = await build({
        entryPoints: [absSrc],
        bundle: true,
        platform: 'node',
        format: 'cjs',
        target: 'node20',
        write: false,
        banner: {js: BANNER}
    })
    const contents = result.outputFiles[0].text

    if (CHECK_ONLY) {
        try {
            const existing = readFileSync(absOut, 'utf8')
            if (existing === contents) {
                console.log(`OK     ${out}`)
                return true
            }
            console.error(`DRIFT  ${out} — rerun \`npm run build:scripts\``)
            return false
        } catch (e) {
            console.error(`MISSING  ${out}`)
            return false
        }
    }

    writeFileSync(absOut, contents)
    console.log(`wrote  ${out}`)
    return true
}

;(async () => {
    let allOk = true
    for (const s of SCRIPTS) {
        const ok = await buildOne(s)
        if (!ok) allOk = false
    }
    if (CHECK_ONLY && !allOk) process.exit(1)
})()
